import { defineField, defineType } from 'sanity'
export default defineType({
  name: 'article', title: 'Article', type: 'document',
  groups: [
    { name: 'content', title: 'Content' }, { name: 'seo', title: 'SEO' },
    { name: 'multisite', title: 'Multi-Site' }, { name: 'hrlake', title: 'HRLake' },
    { name: 'abcm', title: 'ABCM Metadata' }, { name: 'links', title: 'Article Buttons' },
  ],
  fields: [
    defineField({ name: 'title', title: 'Title', type: 'string', group: 'content', validation: (Rule) => Rule.required() }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', group: 'content', options: { source: 'title', maxLength: 200 }, validation: (Rule) => Rule.required() }),
    defineField({ name: 'excerpt', title: 'Excerpt', type: 'text', rows: 3, group: 'content' }),
    defineField({ name: 'body', title: 'Body', type: 'array', group: 'content', of: [{ type: 'block' }, { type: 'tableBlock' }, { type: 'quizbankBlock' }, { type: 'image', options: { hotspot: true }, fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })] }] }),
    defineField({ name: 'featuredImage', title: 'Featured Image', type: 'image', group: 'content', options: { hotspot: true }, fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })] }),
    defineField({ name: 'author', title: 'Author', type: 'reference', group: 'content', to: [{ type: 'author' }] }),
    defineField({ name: 'categories', title: 'Categories', type: 'array', group: 'content', of: [{ type: 'reference', to: [{ type: 'category' }] }] }),
    defineField({ name: 'tags', title: 'Tags', type: 'array', group: 'content', of: [{ type: 'string' }], options: { layout: 'tags' } }),
    defineField({ name: 'difficulty', title: 'Difficulty', type: 'string', group: 'content', options: { list: [{ title: 'Beginner', value: 'beginner' }, { title: 'Intermediate', value: 'intermediate' }, { title: 'Advanced', value: 'advanced' }], layout: 'radio' } }),
    defineField({ name: 'contentType', title: 'Content Type', type: 'string', group: 'content', options: { list: [{ title: 'Country Report', value: 'country-report' }, { title: 'Explainer', value: 'explainer' }, { title: 'Technical', value: 'technical' }, { title: 'HR Management', value: 'hr-management' }, { title: 'EOR Guide', value: 'eor-guide' }, { title: 'Tax Guide', value: 'tax-guide' }, { title: 'News', value: 'news' }, { title: 'Tool Guide', value: 'tool-guide' }, { title: 'Article', value: 'article' }, { title: 'Guide', value: 'guide' }, { title: 'Tutorial', value: 'tutorial' }] } }),
    defineField({ name: 'publishedAt', title: 'Published At', type: 'datetime', group: 'content' }),
    defineField({ name: 'lastReviewed', title: 'Last Reviewed', type: 'datetime', group: 'content' }),
    defineField({ name: 'seoTitle', title: 'SEO Title', type: 'string', group: 'seo', validation: (Rule) => Rule.max(60) }),
    defineField({ name: 'seoDescription', title: 'SEO Description', type: 'text', rows: 2, group: 'seo', validation: (Rule) => Rule.max(160) }),
    defineField({ name: 'canonicalOwner', title: 'Canonical Owner', type: 'string', group: 'multisite', options: { list: [{ title: 'AccountingBody', value: 'accountingbody' }, { title: 'HRLake', value: 'hrlake' }, { title: 'EthioTax', value: 'ethiotax' }], layout: 'radio' }, validation: (Rule) => Rule.required() }),
    defineField({ name: 'showOnSites', title: 'Show On Sites', type: 'array', group: 'multisite', of: [{ type: 'string' }], options: { list: [{ title: 'AccountingBody', value: 'accountingbody' }, { title: 'HRLake', value: 'hrlake' }, { title: 'EthioTax', value: 'ethiotax' }], layout: 'grid' } }),
    defineField({ name: 'mcqUrl', title: 'MCQ Practice URL', type: 'url', group: 'links' }),
    defineField({ name: 'learningUrl', title: 'Learning URL', type: 'url', group: 'links' }),
    defineField({ name: 'shortQuestionsUrl', title: 'Short Questions URL', type: 'url', group: 'links' }),
    defineField({ name: 'scenarioUrl', title: 'Scenario URL', type: 'url', group: 'links' }),
    defineField({ name: 'countryTags', title: 'Country Tags (ISO2)', type: 'array', group: 'hrlake', description: 'ISO2 country codes this article covers. e.g. GB, US, DE', of: [{ type: 'string' }], options: { layout: 'tags' } }),
    defineField({ name: 'relatedCountryCode', title: 'Primary Country Code', type: 'string', group: 'hrlake', description: 'Single ISO2 code linking to Supabase country data for HRLake AI. e.g. GB' }),
    defineField({ name: 'dataFreshDate', title: 'Data Fresh Date', type: 'date', group: 'hrlake', description: 'Date the data in this article was last verified against official sources.' }),
    defineField({ name: 'requiresQuarterlyReview', title: 'Requires Quarterly Review', type: 'boolean', group: 'hrlake', initialValue: false, description: 'Flag articles containing tax rates, SS rates or employment law that change regularly.' }),
    defineField({ name: 'aiSummary', title: 'AI Summary', type: 'text', rows: 4, group: 'hrlake', description: 'Short plain-text summary optimised for RAG retrieval. Write in clear factual sentences.' }),
    defineField({ name: 'aiKeyTerms', title: 'AI Key Terms', type: 'array', group: 'hrlake', description: 'Key terms for vector indexing. e.g. employer NI, PAYE, minimum wage', of: [{ type: 'string' }], options: { layout: 'tags' } }),
    defineField({ name: 'aiSearchable', title: 'Include in AI Knowledge Base', type: 'boolean', group: 'hrlake', initialValue: true, description: 'When enabled this article is indexed into the HRLake AI knowledge base.' }),
    defineField({ name: 'abcmDifficulty', title: 'ABCM Difficulty', type: 'string', group: 'abcm' }),
    defineField({ name: 'abcmFramework', title: 'ABCM Framework', type: 'string', group: 'abcm' }),
    defineField({ name: 'abcmExamBody', title: 'ABCM Exam Body', type: 'string', group: 'abcm' }),
    defineField({ name: 'abcmQuestionType', title: 'ABCM Question Type', type: 'string', group: 'abcm' }),
  ],
  preview: {
    select: { title: 'title', author: 'author.name', media: 'featuredImage', sites: 'showOnSites' },
    prepare({ title, author, media, sites }: any) { return { title, subtitle: `${author ?? 'No author'} · ${sites?.join(', ') ?? ''}`, media } },
  },
})
